// Craftvalley — Mock Data (producers, products, events, news)

const CV_DATA = {

  producers: [
    {
      id: "sozan",
      nameEn: "Sozan Studio",
      nameJa: "蒼山工房",
      craftEn: "Takaoka Copper Casting",
      craftJa: "高岡銅器",
      city: "Takaoka City, Toyama",
      cityJa: "富山県高岡市",
      established: 1952,
      generation: 3,
      artisanEn: "So Yamada",
      artisanJa: "山田 蒼",
      bioEn: "Sozan Studio has been casting copper in Takaoka for three generations. Using traditional lost-wax and sand-cast techniques, So Yamada creates vessels and sculptures that balance 400-year-old Takaoka craft tradition with contemporary sensibility. His signature 'Yamabuki' vase series has won recognition at the Japan Craft Design Award.",
      bioJa: "蒼山工房は高岡で三代にわたって銅器を鋳造してきました。伝統的なロストワックスと砂型鋳造の技法を用いて、山田蒼は400年の高岡銅器の伝統と現代的な感覚を両立した器と彫刻を生み出しています。代表作「山吹」花瓶シリーズは日本クラフトデザイン賞で受賞しています。",
      accessEn: "From Toyama Station, take JR Hokuriku Line to Takaoka Station (approx. 15 min, ¥330). Then taxi approx. 10 min to Sozan Studio (Takaoka Casting District). Alternatively, walk 20 min from Takaoka Station.",
      accessJa: "富山駅からJR北陸本線で高岡駅まで約15分（¥330）。高岡駅からタクシーで約10分（鋳物師町方面）。または高岡駅から徒歩約20分。",
      tags: ["copper", "casting", "decorative", "award-winning"],
      image: "PLACEHOLDER — Aerial or close-up photo of Takaoka copper workshop showing casting process; warm golden light on metal",
      products: ["yamabuki-vase", "kanade-bell", "copper-sake-cup"],
    },
    {
      id: "hakuho",
      nameEn: "Hakuho Paper Studio",
      nameJa: "白峰紙工房",
      craftEn: "Etchu Washi Papermaking",
      craftJa: "越中和紙",
      city: "Nanto City, Toyama",
      cityJa: "富山県南砺市",
      established: 1887,
      generation: 5,
      artisanEn: "Yuki Tanaka",
      artisanJa: "田中 雪",
      bioEn: "The Tanaka family has been making Etchu washi in the Toga valley since the Meiji era. The cold, clear snowmelt water of the Nanto mountains gives Hakuho paper its legendary strength and translucency. Fifth-generation master Yuki Tanaka experiments with embedding pressed alpine flowers and ferns, creating washi that doubles as botanical art.",
      bioJa: "田中家は明治時代から利賀渓谷で越中和紙を漉き続けています。南砺の山々の冷たく澄んだ雪解け水が、白峰紙の伝説的な強度と透明感を生み出します。五代目の田中雪は、押し花や山野草を漉き込む実験を重ね、植物画にもなる和紙を生み出しています。",
      accessEn: "From Toyama Station, take JR Johana Line to Fukumitsu Station (approx. 40 min, ¥660). Then taxi approx. 20 min to Hakuho Studio (Toga-mura area). Please call ahead to arrange entry.",
      accessJa: "富山駅からJR城端線で福光駅まで約40分（¥660）。福光駅からタクシーで約20分（利賀村方面）。見学の際は事前にご連絡ください。",
      tags: ["washi", "paper", "botanical", "traditional"],
      image: "PLACEHOLDER — Artisan dipping washi screen in clear water; bright natural light; mountain backdrop visible through window",
      products: ["washi-notebook", "botanical-washi-sheet", "washi-lamp"],
    },
    {
      id: "shoki",
      nameEn: "Shoki Lacquer Studio",
      nameJa: "匠木工房",
      craftEn: "Hida Shunkei Lacquerware",
      craftJa: "飛騨春慶塗",
      city: "Hida City, Gifu",
      cityJa: "岐阜県飛騨市",
      established: 1968,
      generation: 2,
      artisanEn: "Takumi Kawakami",
      artisanJa: "川上 匠",
      bioEn: "Hida Shunkei lacquer is unique for its transparent finish that allows the natural wood grain to glow through layers of persimmon tannin and lacquer. Takumi Kawakami inherited his father's studio and has expanded the range to include modern tableware shapes that appeal to international buyers while honoring the 400-year-old Shunkei tradition.",
      bioJa: "飛騨春慶塗は、柿渋と漆の層を通して木目が輝く透明仕上げが特徴です。川上匠は父の工房を継ぎ、400年の春慶塗の伝統を守りながら、海外バイヤーにも響くモダンな食器形状へ展開しています。",
      accessEn: "From Toyama Station, take JR Takayama Main Line to Hida-Furukawa Station (approx. 45 min, ¥1,140). Walk approx. 10 min from the station (north exit, follow the Arako River path). Studio is signposted from the station.",
      accessJa: "富山駅からJR高山本線で飛騨古川駅まで約45分（¥1,140）。駅の北口から荒城川沿いを徒歩約10分。工房まで案内表示があります。",
      tags: ["lacquer", "shunkei", "tableware", "wood"],
      image: "PLACEHOLDER — Close-up of amber-toned lacquerware with wood grain visible; natural side lighting; traditional workshop background",
      products: ["shunkei-tray", "shunkei-bowls-set", "shunkei-chopsticks"],
    },
    {
      id: "tesshin",
      nameEn: "Tesshin Cutlery Studio",
      nameJa: "鉄心工房",
      craftEn: "Kaga Cutlery",
      craftJa: "加賀刃物",
      city: "Komatsu City, Ishikawa",
      cityJa: "石川県小松市",
      established: 1935,
      generation: 4,
      artisanEn: "Tetsuo Mori",
      artisanJa: "森 鉄男",
      bioEn: "The Mori family forge in Komatsu has produced Kaga blades since 1935, using high-carbon steel folded in the tradition of Japanese swordsmiths. Fourth-generation Tetsuo Mori specializes in kitchen knives for professional and home cooks, each blade hand-ground and edge-tested before leaving the studio. Every knife comes with a certificate of authenticity and Tetsuo's stamp.",
      bioJa: "小松市の森家の鍛冶場は1935年から加賀刃物を製造しており、日本刀の伝統を受け継ぐ高炭素鋼の折り返し鍛錬を用いています。四代目の森鉄男はプロ・家庭料理人向けの包丁を専門とし、すべての刃を手研ぎし、出荷前に切れ味を確認しています。すべての包丁には真正証明書と鉄男の刻印が付属します。",
      accessEn: "From Toyama Station, take Hokuriku Shinkansen to Kaga-Onsen Station (approx. 20 min, ¥2,680). Then taxi approx. 15 min to Tesshin Studio in central Komatsu.",
      accessJa: "富山駅から北陸新幹線で加賀温泉駅まで約20分（¥2,680）。加賀温泉駅からタクシーで小松市中心部の鉄心工房まで約15分。",
      tags: ["knives", "forging", "steel", "professional"],
      image: "PLACEHOLDER — Blacksmith forging a blade over coal fire; sparks and glowing steel; dramatic dark workshop atmosphere",
      products: ["kaga-gyuto-180", "kaga-nakiri", "kaga-petty"],
    },
    {
      id: "ecchu-beer",
      nameEn: "Ecchu Craft Brewery",
      nameJa: "越中麦酒醸造所",
      craftEn: "Craft Beer (Rice & Barley)",
      craftJa: "クラフトビール（米・麦）",
      city: "Imizu City, Toyama",
      cityJa: "富山県射水市",
      established: 2018,
      generation: 1,
      artisanEn: "Hiroshi Matsumoto",
      artisanJa: "松本 啓",
      bioEn: "Hiroshi Matsumoto founded Ecchu Craft Brewery in 2018, drawing on Toyama's legendary rice and pristine snowmelt water. The brewery's flagship 'Tateyama White' uses koji — the same fermentation starter used in sake — to create a hazy wheat beer with umami depth unlike any Western craft brew. Seasonal releases feature locally foraged ingredients.",
      bioJa: "松本啓は2018年に越中麦酒醸造所を設立。富山の銘柄米と雪解けの清水を活かして醸造しています。フラッグシップの「立山ホワイト」は、日本酒と同じ麹を用い、西洋のクラフトビールにはない旨味を持つヘイジーウィートビールです。季節限定品は地元の野草や山菜を使用しています。",
      accessEn: "From Toyama Station, take Ainokaze Toyama Railway to Nishi-Toyama Station (approx. 8 min, ¥240). Then taxi approx. 5 min. Alternatively, take Manyo Line tram from Takaoka.",
      accessJa: "富山駅からあいの風とやま鉄道で西富山駅まで約8分（¥240）、タクシーで約5分。または高岡から万葉線で利用可能。",
      tags: ["beer", "koji", "fermentation", "rice"],
      image: "PLACEHOLDER — Rows of wooden casks in modern brewery with mountain view window; warm amber lighting; condensation on tanks",
      products: ["tateyama-white-6pack", "seasonal-koshihikari-ale", "brewery-set"],
    },
    {
      id: "hida-koji",
      nameEn: "Hida Koji Studio",
      nameJa: "飛騨こうじ工房",
      craftEn: "Traditional Koji Fermentation",
      craftJa: "伝統麹発酵",
      city: "Hida City, Gifu",
      cityJa: "岐阜県飛騨市",
      established: 2015,
      generation: 1,
      artisanEn: "Kojiko Nakamura",
      artisanJa: "中村 麹子",
      bioEn: "Koji — the 'national mold' of Japan — transforms simple ingredients into extraordinary flavors. Kojiko Nakamura trained under Hida miso masters before founding her own studio in 2015. Her shio-koji and white miso have attracted attention from Michelin-starred chefs in New York. She ships direct-to-consumer across the US with cold-pack guarantee.",
      bioJa: "日本の「国菌」である麹は、シンプルな食材を非凡な味に変えます。中村麹子は飛騨の味噌職人のもとで修行の後、2015年に自身の工房を設立。塩麹と白味噌はニューヨークのミシュランシェフからも注目されています。全米への冷蔵直送に対応しています。",
      accessEn: "From Toyama Station, take JR Takayama Main Line to Hida-Furukawa Station (approx. 45 min, ¥1,140). Walk approx. 15 min from station (south along Miya River). Call ahead for workshop visits.",
      accessJa: "富山駅からJR高山本線で飛騨古川駅まで約45分（¥1,140）。駅から宮川沿いを南に徒歩約15分。工房見学は事前予約をお願いします。",
      tags: ["koji", "miso", "fermentation", "food", "export-ready"],
      image: "PLACEHOLDER — Overhead view of koji rice in traditional cedar trays; warm white bloom of koji mold; craftsperson's hands visible",
      products: ["shio-koji-500g", "hida-white-miso", "amazake-concentrate"],
    },
  ],

  products: [
    {
      id: "yamabuki-vase",
      nameEn: "Yamabuki Copper Vase",
      nameJa: "山吹 銅花瓶",
      producerId: "sozan",
      price: 280,
      currency: "USD",
      category: "craft",
      descEn: "Hand-cast using 400-year-old Takaoka sand-casting techniques, this vase takes its name from the mountain rose (yamabuki) that blooms across Toyama each spring. Each piece varies slightly — a mark of authenticity. Comes in a paulownia wood gift box.",
      descJa: "高岡400年の砂型鋳造技法で手づくり。山吹の名は、毎春富山に咲き誇るヤマブキの花に由来します。一点一点わずかに表情が異なるのが本物の証。桐箱入り。",
      dimensions: "H 28cm × W 14cm",
      weight: "1.2kg",
      material: "Takaoka cast copper, natural patina finish",
      materialJa: "高岡銅器（砂型鋳造）、天然緑青仕上げ",
      inStock: true,
      image: "PLACEHOLDER — Studio photo of copper vase on neutral linen background; slight left lighting to show surface texture; small yamabuki flower beside it",
    },
    {
      id: "kanade-bell",
      nameEn: "Kanade Wind Bell",
      nameJa: "奏 風鈴",
      producerId: "sozan",
      price: 95,
      currency: "USD",
      category: "craft",
      descEn: "A hanging copper wind bell cast in the Takaoka tradition. 'Kanade' means 'to play music.' The clear, resonant tone is designed to carry across a garden or porch. Includes a Japanese calligraphy paper tag.",
      descJa: "高岡伝統の銅製風鈴。「奏」は音楽を奏でるという意味。庭やテラスに澄み渡る音色が響きます。和紙の短冊付き。",
      dimensions: "H 12cm × W 8cm",
      weight: "180g",
      material: "Cast copper",
      materialJa: "銅器（鋳造）",
      inStock: true,
      image: "PLACEHOLDER — Wind bell hanging against soft-focus garden greenery; late-afternoon side light; washi tag visible",
    },
    {
      id: "washi-notebook",
      nameEn: "Botanical Washi Notebook",
      nameJa: "草花和紙 ノート",
      producerId: "hakuho",
      price: 45,
      currency: "USD",
      category: "paper",
      descEn: "Handmade Etchu washi cover with pressed alpine flowers embedded during papermaking. Each notebook is unique — the flower arrangement cannot be replicated. 48 pages of smooth writing washi interior. A5 size.",
      descJa: "漉き込み時に高山植物を埋め込んだ越中和紙の表紙。一点ものの花のレイアウトは再現不可能。内側は書き心地の良い和紙48ページ。A5サイズ。",
      dimensions: "A5 (148×210mm), 48 pages",
      weight: "120g",
      material: "Etchu washi (mulberry fiber)",
      materialJa: "越中和紙（楮繊維）",
      inStock: true,
      image: "PLACEHOLDER — Open notebook on wooden desk; pressed alpine flowers visible on cover; afternoon window light from left",
    },
    {
      id: "shunkei-tray",
      nameEn: "Shunkei Tea Tray",
      nameJa: "春慶塗 茶盆",
      producerId: "shoki",
      price: 185,
      currency: "USD",
      category: "craft",
      descEn: "Hida Shunkei's translucent lacquer technique reveals the natural grain of Hida hinoki (Japanese cypress), creating a warm amber glow. This tea tray is sized for two teacups. Suitable for daily use — lacquer strengthens with age and use.",
      descJa: "飛騨春慶塗の透明漆技法で飛騨ヒノキの木目を活かした茶盆。茶碗2つが置けるサイズ。日常使いに適しており、使い込むほど漆が育ちます。",
      dimensions: "36cm × 24cm × 2.5cm",
      weight: "320g",
      material: "Hida hinoki, Shunkei persimmon tannin lacquer",
      materialJa: "飛騨ヒノキ、柿渋春慶漆",
      inStock: true,
      image: "PLACEHOLDER — Tea tray on tatami mat with two small celadon teacups; soft morning light; wood grain warmly visible through lacquer",
    },
    {
      id: "kaga-gyuto-180",
      nameEn: "Kaga Gyuto Chef's Knife 180mm",
      nameJa: "加賀牛刀 180mm",
      producerId: "tesshin",
      price: 320,
      currency: "USD",
      category: "craft",
      descEn: "A professional-grade gyuto (Western-style chef's knife) hand-forged from high-carbon Kaga steel. 180mm blade, double-bevel edge at 15°/side. Magnolia wood handle. Comes with signed certificate of authenticity and storage cloth. Recommended: hand-wash only.",
      descJa: "高炭素加賀鋼を手打ち鍛造したプロ仕様の牛刀。刃渡り180mm、両刃15°。木蓮材の柄。真正証明書（署名入り）と保管用クロス付き。水洗いのみ推奨。",
      dimensions: "Blade: 180mm, Handle: 135mm",
      weight: "185g",
      material: "High-carbon Kaga steel (HRC 62), magnolia handle",
      materialJa: "高炭素加賀鋼（硬度HRC62）、木蓮材",
      inStock: true,
      image: "PLACEHOLDER — Chef's knife on dark slate surface; blade at 45° angle showing edge geometry; subtle reflection; white background bokeh",
    },
    {
      id: "tateyama-white-6pack",
      nameEn: "Tateyama White Ale 6-Pack",
      nameJa: "立山ホワイト 6本セット",
      producerId: "ecchu-beer",
      price: 42,
      currency: "USD",
      category: "food",
      descEn: "Tateyama White is a hazy wheat ale brewed with koji rice for added umami and a clean finish. Inspired by the snowfields of Mt. Tateyama that feed Toyama's rivers. Pairs beautifully with seafood, sushi, and mild cheeses. 5.2% ABV, 350ml cans.",
      descJa: "麹米を用いて旨味と後味のキレを加えたヘイジーウィートエール。富山の川を育む立山の雪原にインスパイアされています。海鮮・寿司・クリーミーチーズに合います。アルコール度数5.2%、350ml缶。",
      dimensions: "6 × 350ml cans",
      weight: "2.4kg",
      material: "Water, barley, wheat, koji rice, hops",
      materialJa: "水、大麦麦芽、小麦、麹米、ホップ",
      inStock: true,
      image: "PLACEHOLDER — Six cans arranged on mountain stream rocks with Tateyama peaks behind; golden afternoon light; condensation on cans",
    },
    {
      id: "shio-koji-500g",
      nameEn: "Hida Shio-Koji (500g)",
      nameJa: "飛騨塩麹 500g",
      producerId: "hida-koji",
      price: 28,
      currency: "USD",
      category: "food",
      descEn: "Shio-koji is a centuries-old Japanese seasoning of salt-fermented rice koji. Rub it on proteins before cooking to tenderize and add deep umami. Michelin chefs in New York use Nakamura-san's shio-koji in their kitchens. Ships frozen with ice pack included.",
      descJa: "塩麹は数百年の歴史を持つ塩発酵の麹調味料。タンパク質に揉み込むことで柔らかくし、旨味を加えます。中村さんの塩麹はニューヨークのミシュランシェフのキッチンでも使われています。保冷剤入り冷凍発送。",
      dimensions: "500g",
      weight: "580g (with packaging)",
      material: "Hida rice, sea salt, Aspergillus oryzae (koji mold)",
      materialJa: "飛騨米、海塩、米麹（アスペルギルス・オリゼー）",
      inStock: true,
      image: "PLACEHOLDER — Ceramic pot of shio-koji on wooden cutting board with fresh salmon and vegetables; bright kitchen daylight",
    },
    {
      id: "copper-sake-cup",
      nameEn: "Takaoka Copper Sake Cup",
      nameJa: "高岡銅器 盃",
      producerId: "sozan",
      price: 68,
      currency: "USD",
      category: "craft",
      descEn: "A traditional sake cup (sakazuki) cast in Takaoka copper. Copper gently alters the flavor of sake and sake-based cocktails — a discovery made centuries ago by Japanese sake brewers. A gift loved by sake enthusiasts worldwide.",
      descJa: "高岡銅器で鋳造した伝統的な盃。銅は日本酒やカクテルの風味を穏やかに変化させ、これは何百年も前に酒蔵で発見された知恵です。日本酒好きへの贈り物として世界中で人気です。",
      dimensions: "Ø 9cm × H 3cm",
      weight: "95g",
      material: "Cast copper, wax-finished interior",
      materialJa: "銅器（鋳造）、内面ワックス仕上げ",
      inStock: true,
      image: "PLACEHOLDER — Two copper sake cups on black lacquer tray with small sake carafe; candlelight ambiance; minimalist composition",
    },
  ],

  events: {
    upcoming: [
      {
        id: "ev-2026-07",
        date: "2026-07-12",
        endDate: "2026-07-14",
        titleEn: "Craftvalley Summer Festival",
        titleJa: "クラフトバレー夏まつり",
        locationEn: "Takaoka City Central Plaza, Toyama",
        locationJa: "富山県高岡市中央広場",
        descEn: "Three days of artisan demonstrations, tastings and workshops. Meet the makers behind Craftvalley products and watch live casting, paper-making and lacquering. Free admission.",
        descJa: "3日間の職人実演・試食・ワークショップ。鋳造・和紙漉き・漆塗りの実演を目前で体験。入場無料。",
        type: "festival",
        registerUrl: "#",
      },
      {
        id: "ev-2026-08",
        date: "2026-08-20",
        endDate: "2026-08-25",
        titleEn: "Craftvalley NYC Pop-Up Shop",
        titleJa: "クラフトバレー NYC ポップアップショップ",
        locationEn: "SoHo, New York City, USA",
        locationJa: "米国・ニューヨーク市ソーホー地区",
        descEn: "Six days in New York's SoHo district. Browse the full Craftvalley collection in person, meet two visiting artisans, and enjoy a sake-pairing evening on Aug. 22.",
        descJa: "ニューヨーク・ソーホー地区にて6日間開催。全コレクションの展示販売、職人2名が来米。8/22には日本酒ペアリングイベントも。",
        type: "popup",
        registerUrl: "#",
      },
      {
        id: "ev-2026-09",
        date: "2026-09-15",
        endDate: "2026-09-17",
        titleEn: "Artisan Experience Tour",
        titleJa: "職人体験ツアー",
        locationEn: "Craftvalley Region, Japan (Toyama / Hida / Komatsu)",
        locationJa: "クラフトバレー域（富山・飛騨・小松）",
        descEn: "A 3-day guided tour of Craftvalley workshops for international visitors. Visit six studios, try hands-on craft sessions, and enjoy local food and sake. Accommodation included. Limited to 12 participants.",
        descJa: "海外からのビジター向け3日間の工房ガイドツアー。6工房を訪問し、制作体験・地元食・日本酒を楽しむ。宿泊込み。定員12名。",
        type: "tour",
        registerUrl: "#",
      },
      {
        id: "ev-2026-11",
        date: "2026-11-01",
        endDate: "2026-11-02",
        titleEn: "Holiday Preview Exhibition",
        titleJa: "ホリデーシーズン プレビュー展",
        locationEn: "Komatsu City Cultural Hall, Ishikawa",
        locationJa: "石川県小松市文化ホール",
        descEn: "A curated preview of Craftvalley's holiday gift collection. New products unveiled for the first time. B2B buyers welcome — appointment preferred.",
        descJa: "クラフトバレー・ホリデーギフトコレクションのプレビュー展。新商品が初披露されます。法人バイヤーのご来場も歓迎。予約優先。",
        type: "exhibition",
        registerUrl: "#",
      },
    ],
    past: [
      {
        id: "ev-2024-10",
        date: "2024-10-05",
        endDate: "2024-10-07",
        titleEn: "Craftvalley Launch Exhibition",
        titleJa: "クラフトバレー ローンチ展覧会",
        locationEn: "Takaoka City Museum, Toyama",
        locationJa: "富山県高岡市立博物館",
        descEn: "The inaugural Craftvalley exhibition presented works by all six founding artisans. Over 800 visitors across 3 days. Featured in NHK regional news and Toyama Shimbun.",
        descJa: "クラフトバレー創設6工房の作品を紹介した発足展覧会。3日間で800名以上来場。NHK地方ニュース・富山新聞に掲載。",
        type: "exhibition",
        summary: "800+ visitors, 6 artisans",
        summaryJa: "来場800名以上、6工房参加",
      },
      {
        id: "ev-2024-12",
        date: "2024-12-06",
        endDate: "2024-12-10",
        titleEn: "Holiday Pop-Up — New York City",
        titleJa: "ホリデーポップアップ — ニューヨーク市",
        locationEn: "Chelsea Market, New York City, USA",
        locationJa: "米国・ニューヨーク市チェルシーマーケット",
        descEn: "Craftvalley's first overseas appearance at Chelsea Market. Over $40,000 in product sales. Press coverage in New York Magazine. Koji tastings were the most popular activity.",
        descJa: "クラフトバレー初の海外出展。売上4万ドル超。ニューヨーク・マガジンに掲載。麹の試食が最も人気を集めました。",
        type: "popup",
        summary: "$40K+ sales, press coverage",
        summaryJa: "売上4万ドル以上・メディア掲載",
      },
      {
        id: "ev-2025-02",
        date: "2025-02-14",
        endDate: "2025-02-14",
        titleEn: "Sake & Craft Pairing Evening",
        titleJa: "日本酒と工芸品のペアリングの夕べ",
        locationEn: "Toyama Castle Cultural Hall",
        locationJa: "富山城文化会館",
        descEn: "An intimate evening pairing Toyama and Hida sake with Craftvalley craft objects. 60 guests including 15 international participants. Collaborative event with Toyama Sake Brewers Association.",
        descJa: "富山・飛騨の日本酒とクラフトバレー工芸品のペアリングイベント。60名参加（海外15名含む）。富山酒造組合との共同開催。",
        type: "tasting",
        summary: "60 guests, 8 sake producers",
        summaryJa: "60名参加・8酒蔵協力",
      },
      {
        id: "ev-2025-04",
        date: "2025-04-19",
        endDate: "2025-04-21",
        titleEn: "Spring Artisan Workshop Series",
        titleJa: "春の職人ワークショップシリーズ",
        locationEn: "Hida-Furukawa Town, Gifu",
        locationJa: "岐阜県飛騨市古川町",
        descEn: "Three days of hands-on workshops in lacquerware, koji making and copper engraving. 45 participants from Japan and overseas. Fully booked within 2 weeks of announcement.",
        descJa: "漆・麹・銅刻の3日間体験ワークショップ。国内外から45名参加。告知から2週間で満員。",
        type: "workshop",
        summary: "45 participants, 3 disciplines",
        summaryJa: "45名参加・3分野のワークショップ",
      },
    ],
  },

  news: [
    {
      id: "news-2026-02-20",
      date: "2026-02-20",
      category: "event",
      titleEn: "Summer Festival 2026 Announced — Free Entry",
      titleJa: "夏まつり2026開催決定 — 入場無料",
      summaryEn: "The Craftvalley Summer Festival returns to Takaoka this July 12–14. Six artisans, live demonstrations, food stalls and children's craft activities. All free.",
      summaryJa: "クラフトバレー夏まつりが7月12〜14日に高岡で開催決定。6工房による実演・屋台・子ども向けワークショップ。全て入場無料。",
      image: "PLACEHOLDER — Festival atmosphere at previous event; people watching copper casting demonstration; summer day",
    },
    {
      id: "news-2025-05-01",
      date: "2025-05-01",
      category: "press",
      titleEn: "Craftvalley Featured in Bon Appétit Magazine",
      titleJa: "ボン・アペティ誌にクラフトバレーが掲載",
      summaryEn: "Bon Appétit's May issue features a 4-page spread on Craftvalley's fermented food producers, calling Hida Koji Studio 'a revelation for American home cooks.'",
      summaryJa: "ボン・アペティ誌5月号で飛騨こうじ工房が「アメリカのホームクックにとっての発見」と4ページにわたって特集されました。",
      image: "PLACEHOLDER — Magazine cover or page spread showing food article; editorial styling with koji products",
    },
    {
      id: "news-2025-04-10",
      date: "2025-04-10",
      category: "producer",
      titleEn: "New Artisan Joins Craftvalley: Nanto Textile Studio",
      titleJa: "新しい職人が参加：南砺市の染織工房",
      summaryEn: "We welcome Nishiki Weaving Studio from Nanto City to the Craftvalley family. Their hand-woven Etchu cotton will debut in the summer collection.",
      summaryJa: "南砺市の錦織り工房がクラフトバレーに参加しました。手織りの越中木綿は夏コレクションでデビュー予定です。",
      image: "PLACEHOLDER — Portrait of textile artisan at loom; natural studio light; colorful thread spools in background",
    },
    {
      id: "news-2025-03-15",
      date: "2025-03-15",
      category: "shop",
      titleEn: "US Online Shop Now Open — Shipping to All 50 States",
      titleJa: "米国向けオンラインショップ開設 — 全50州発送",
      summaryEn: "Our US online shop is now live. All orders ship from our Toyama fulfillment center with DHL Express (3–5 business days). Free shipping on orders over $150.",
      summaryJa: "米国向けオンラインショップが開設しました。全注文は富山の発送センターからDHLエクスプレスで3〜5営業日でお届け。150ドル以上送料無料。",
      image: "PLACEHOLDER — Products arranged on white background for e-commerce; clean, minimalist packaging visible",
    },
  ],
};
